### ISSUE TITLE
errors in simulation.py

### ISSUE THREAD

**Issue by adrienneskywalker** [Ash530888/LDS_KF_KS#2]
Hello, I tried to run simulation.py and there are some errors appearing.

PS C:\Users\29594\Downloads\LDS_KF_KS> python simulation.py
Traceback (most recent call last):
  File "C:\Users\29594\Downloads\LDS_KF_KS\simulation.py", line 284, in <module>        
    main()
  File "C:\Users\29594\Downloads\LDS_KF_KS\simulation.py", line 268, in main
    fd_v1, fd_v2 = plot.plotVelocities(true_vel, measured, filtered["xnn"], smoothed["xnN"], dt, N)
  File "C:\Users\29594\Downloads\LDS_KF_KS\plot.py", line 121, in plotVelocities        
    if true_vel!=False:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
PS C:\Users\29594\Downloads\LDS_KF_KS> 

also I want to ask what version of python are you using to run this script? thanks in advance!

**Comment by Ash530888** [comment]
Hi adrienneskywalker,

Thank you for bringing this to my attention.

I actually do not remember which Python version I originally developed and ran this script in (lesson: always make a requirements.txt and list dependencies and versions for all projects!!). And tried both a version 2 and 3 and found errors.

But I have now fixed the code (after a quick [stackoverflow](https://stackoverflow.com/questions/10062954/valueerror-the-truth-value-of-an-array-with-more-than-one-element-is-ambiguous) search to fix this error) and the output now looks right.

I now ran it using an environment with Python 3.9.13.

I highly recommend heading over to [Joaquin Rapela's Github repo](https://github.com/joacorapela/lds_python.git) for documentation and Python code about LDS, KF, KS.
